# Generated by Django 2.2.10 on 2020-02-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_auth', '0002_auto_20200222_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='expires_at',
            new_name='expires_in',
        ),
    ]
