# Generated by Django 2.2.10 on 2020-02-24 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_auth', '0003_auto_20200222_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='token',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 24, 1, 58, 25, 597921)),
            preserve_default=False,
        ),
    ]
